---
- hosts: all
  sudo: true
  gather_facts: false
  vars:
    # state: present
    state: latest
  roles:
    - { role: common }
    - { role: autoupgrade }
    - { role: docker, ca: docker-registry, client: vserver, registry: "vafer.org:5000", compose: default }
    - { role: webserver }
    - { role: bouncer }
