---

# TODO merge sites into host aliases
# - name: build hosts file
#   lineinfile:
#     dest:/etc/hosts
#     regexp: '{{ hostvars[item].ansible_hostname }}$'
#     line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ hostvars[item].ansible_hostname }}'
#     state: present
#   when: hostvars[item].ansible_default_ipv4.address is defined
#   with_items: groups['all']
