---
  
- file: path={{item}} owner=root group=daemon mode=750 state=directory
  with_items:
    - /srv/registry
    - /srv/registry/config
    - /srv/registry/config/tls

- file: path={{item}} owner=root group=daemon mode=770 state=directory
  with_items:
    - /srv/registry/storage

- copy:
    src: "{{item}}"
    dest: /srv/registry/config/tls
    owner: root
    group: daemon
    mode: 0440
  with_items:
    - /Users/tcurdt/Projects/ca/vafer.org/ca/ca.crt
    - /Users/tcurdt/Projects/ca/vafer.org/servers/vafer.org/server.crt
    - /Users/tcurdt/Projects/ca/vafer.org/servers/vafer.org/server.key
  tags: certs

- name: docker registry config
  template:
    src: registry.cfg
    dest: /srv/registry/config/config.yml
